package com.harine.virgotest.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.harine.virgotest.data.bean.ImageItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_ITEM".
*/
public class ImageItemDao extends AbstractDao<ImageItem, Long> {

    public static final String TABLENAME = "IMAGE_ITEM";

    /**
     * Properties of entity ImageItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PId = new Property(1, String.class, "pId", false, "P_ID");
        public final static Property ResId = new Property(2, String.class, "resId", false, "RES_ID");
        public final static Property AreaId = new Property(3, String.class, "areaId", false, "AREA_ID");
        public final static Property Path = new Property(4, String.class, "path", false, "PATH");
        public final static Property StartTime = new Property(5, String.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(6, String.class, "endTime", false, "END_TIME");
        public final static Property Duration = new Property(7, int.class, "duration", false, "DURATION");
        public final static Property Times = new Property(8, int.class, "times", false, "TIMES");
        public final static Property IsFull = new Property(9, boolean.class, "isFull", false, "IS_FULL");
    }


    public ImageItemDao(DaoConfig config) {
        super(config);
    }
    
    public ImageItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"P_ID\" TEXT," + // 1: pId
                "\"RES_ID\" TEXT," + // 2: resId
                "\"AREA_ID\" TEXT," + // 3: areaId
                "\"PATH\" TEXT," + // 4: path
                "\"START_TIME\" TEXT," + // 5: startTime
                "\"END_TIME\" TEXT," + // 6: endTime
                "\"DURATION\" INTEGER NOT NULL ," + // 7: duration
                "\"TIMES\" INTEGER NOT NULL ," + // 8: times
                "\"IS_FULL\" INTEGER NOT NULL );"); // 9: isFull
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImageItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String pId = entity.getPId();
        if (pId != null) {
            stmt.bindString(2, pId);
        }
 
        String resId = entity.getResId();
        if (resId != null) {
            stmt.bindString(3, resId);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(4, areaId);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(5, path);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(6, startTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(7, endTime);
        }
        stmt.bindLong(8, entity.getDuration());
        stmt.bindLong(9, entity.getTimes());
        stmt.bindLong(10, entity.getIsFull() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImageItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String pId = entity.getPId();
        if (pId != null) {
            stmt.bindString(2, pId);
        }
 
        String resId = entity.getResId();
        if (resId != null) {
            stmt.bindString(3, resId);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(4, areaId);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(5, path);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(6, startTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(7, endTime);
        }
        stmt.bindLong(8, entity.getDuration());
        stmt.bindLong(9, entity.getTimes());
        stmt.bindLong(10, entity.getIsFull() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImageItem readEntity(Cursor cursor, int offset) {
        ImageItem entity = new ImageItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // pId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // resId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // areaId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // path
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // startTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // endTime
            cursor.getInt(offset + 7), // duration
            cursor.getInt(offset + 8), // times
            cursor.getShort(offset + 9) != 0 // isFull
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImageItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setResId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAreaId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStartTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEndTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDuration(cursor.getInt(offset + 7));
        entity.setTimes(cursor.getInt(offset + 8));
        entity.setIsFull(cursor.getShort(offset + 9) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImageItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImageItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImageItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
